version: '3.8'

services:
  app:
    container_name: project-manager
    build:
      context: ./
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=mysql://root:Jyoti@2002@mysql-db:3306/projectManagement
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=Jyoti@2002
      - DB_NAME=projectManagement
      - DB_PORT=3306
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - DOCKER_CONTAINER=true
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Jyoti@2002
      MYSQL_DATABASE: projectManagement
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pJyoti@2002"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  mysql-data:
